#!/bin/bash

clear
echo "Creating debian release package"
echo "---------------------------------------------------------------"
sleep 0.5

echo "Step 1: switching to main branch"
git checkout main
sleep 0.5

echo "Step 2: navigating to desktop module"
cd desktop
echo "Current directory: $(pwd)"
sleep 0.5

echo "Step 3: building the .deb package"
./gradlew clean
./gradlew packageReleaseDeb
cd ..
sleep 0.5
echo "Current directory: $(pwd)"

echo "Switching to gh-pages branch"
git checkout gh-pages
echo "Current directory: $(pwd)"

echo "Removing the old .deb package"
rm pool/main/p/pwdgen/*.deb
sleep 0.5

echo "Copying the .deb package to pool/main/p/pwdgen"
cp desktop/build/compose/binaries/main-release/deb/*.deb pool/main/p/pwdgen/
sleep 0.5

echo "New debian package copied to pool/main/p/pwdgen. Showing the folder:"
ls -l pool/main/p/pwdgen
sleep 0.5